import { Button, Input } from "antd";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import style from "../styles/Home.module.css";

const Home =()=> {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.main}>
        <p style={{ fontSize: "32px", fontWeight:'bold' }}>Та нэвтрэх төрлөө сонгоно уу?</p>
        <div className={style.roles}>
          <div className={style.role}>
            <Image src="/images/user.png" alt={""} width={200} height={200} />
            <p>Хэрэглэгч</p>
          </div>
          <div className={style.role}>
            <Image
              src="/images/laborant.png"
              alt={""}
              width={200}
              height={200}
            />
            <p>Лаборант</p>
          </div>
          <div className={style.role}>
            <Image src="/images/admin.png" alt={""} width={200} height={200} />
            <p>Админ</p>
          </div>
        </div>
        <p style={{ fontSize: "16px", fontWeight:'bold', margin: '50px' }}>Тавтай морилно уу хэрэглэгч</p>
        <div className={style.input}>
          <div className={style.span}>КОД</div>
          <Image src="/icons/mail.png" alt={""} width={20} height={20} />
          <Input placeholder="Код" bordered={false}/>
        </div>
        <div className={style.input}>
          <Image src="/icons/lock.png" alt={""} width={20} height={20} />
          <Input placeholder="Нууц үг" bordered={false} />
          <div className={style.reset}>Нууц үг мартсан</div>
        </div>
        <Link className={style.btn} href='admin'>
          <Button className={style.login}>Нэвтрэх</Button>
        </Link>
      </div>
    </>
  );
}

Home.getLayout = function getLayout(page: any) {
  return (
      <>{page}</>
  )
}

export default Home;